# Generated by Django 4.2.2 on 2023-11-23 10:26

from django.db import migrations


def create_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('app', 'MenuItem')
    world_classics = MenuItem.objects.create(title='Мировая классика', url='world_classics')
    russian_classics = MenuItem.objects.create(title='Русская классика', url='russian_classics')
    menu_data = [
        {'title': 'Романы', 'url': 'novels', 'parent': 'world_classics',
         'writers': ['Lev Tolstoy', 'Fedor Dostoevsky', 'Charles Dickens', 'Jane Austen']},
        {'title': 'Поэзия', 'url': 'poetry', 'parent': 'world_classics',
         'poets': ['Alexander Blok', 'Sergey Yesenin', 'Emily Dickinson', 'Pablo Neruda']},
        {'title': 'Романы', 'url': 'novels', 'parent': 'russian_classics',
         'writers': ['Ivan Turgenev', 'Alexander Chekhov']},
        {'title': 'Рассказы', 'url': 'short_stories', 'parent': 'russian_classics',
         'writers': ['Nikolay Gogol', 'Anton Chekhov']}
    ]

    for menu_item_data in menu_data:
        parent = menu_item_data.get('parent')
        parent_menu_item = MenuItem.objects.get(url=parent) if parent else None

        menu_item = MenuItem.objects.create(
            title=menu_item_data['title'],
            url=menu_item_data['url'],
            parent=parent_menu_item
        )

        writers = menu_item_data.get('writers', [])
        poets = menu_item_data.get('poets', [])

        for writer_name in writers:
            last_name = writer_name.split()[-1]
            MenuItem.objects.create(title=writer_name, url=last_name.lower(), parent=menu_item)

        for poet_name in poets:
            last_name = poet_name.split()[-1]
            MenuItem.objects.create(title=poet_name, url=last_name.lower(), parent=menu_item)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_menu_items),
    ]
